
language: python
python:
  - "2.7"
packages:
  - libgdal1-dev
  - libgdal-dev
  - g++
  - python-gdal
# command to install dependencies
install: pip install requirements.txt
# command to run tests
script: converter\manage.py runserver
