
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirement.txt"
# command to run tests
script: 
  "sudo apt-get install -y libgdal1-dev"
  "sudo apt-get install -y libgdal-dev"
  "sudo apt-get install -y g++"
  "sudo apt-get install -y python-gdal"
  "python converter\manage.py runserver"
