
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - ./install.sh
install: pip install -r requirement.txt
# command to run tests
script: converter\manage.py runserver
