
language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - chmod a+x converter/manage.py
  - chmod a+x install.sh
install: ./install.sh
# command to run tests
script: converter/manage.py runserver
